cityon-api:
  image: velocitylab/cityon-api
  ports:
   - "80:8080"
  links:
   - mongodb
  command: java -Djava.security.egd=file:/dev/./urandom -jar -Dspring.data.mongodb.host=mongodb /app.jar
  
mongodb:
  image: mongo
